name: Cleanup Resources

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to cleanup (DANGER: This will delete all resources)'
        required: true
        type: choice
        options:
          - development
          - production
      confirm:
        description: 'Type "DELETE" to confirm resource deletion'
        required: true
        type: string

jobs:
  cleanup:
    name: Cleanup AWS Resources
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DELETE'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Destroy
        working-directory: infrastructure
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve

  confirmation-failed:
    name: Cleanup Cancelled
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm != 'DELETE'
    steps:
      - name: Cancel cleanup
        run: |
          echo "❌ Cleanup cancelled - confirmation input was: '${{ github.event.inputs.confirm }}'"
          echo "To proceed with cleanup, you must type exactly: DELETE"
          exit 1
